//todo: signin and signup form                        [*]
//todo: new article form                              [*]
//todo: fix the data base                             [*]
//todo: render articles in manage base on user id     [*]
//todo: edit and delete articles in manage page       [*]
//todo: store the img                                 [*]
//todo: fix the links                                 [*]
//todo: user name in the header                       [*]
//todo: render articles base on the category          [*]
//todo: article page                                  [*]
//todo: handel comments                               [*]
//todo: footer                                        [*]
//todo: search func                                   [*]
//todo: popular articles                              [*]
//todo: load more button                              [*]
