//todo: signin and signup form                        [*]
//todo: new article form                              [*]
//todo: fix the data base                             [*]
//todo: render articles in manage base on user id     [*]
//todo: edit and delete articles in manage page       [*]
//todo: store the img                                 [*]
//todo: fix the links                                 [*]
//todo: user name in the header                       [*]
//todo: render articles base on the category          [*]
//todo: article page                                  [*]
//todo: handel comments                               [*]
//todo: footer                                        [*]
//todo: search func                                   [*]
//todo: load more button                              [*]

//todo: fix the header                                [*]
//todo: fix imgs heights                              [*]
//todo: footer form                                   [*]
//todo: loadmore position responsive                  [*]
//todo: sidebar search button                         [*]
//todo: sections in category                          [*]
//todo: comment button style                          [*]
//todo: animate the main header search                [*]
//todo: edit card style manage page                   [*]
//todo: fix sections and header links                 [*]
//todo: responsive font size                          []
//todo: testing                                       []
//todo: outsource the validator                       []
